# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hash_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(max_length=100)),
                ('img_addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Original_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('centre', models.IntegerField()),
                ('sec1', models.IntegerField()),
                ('sec2', models.IntegerField()),
                ('sec3', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_text', models.CharField(max_length=100)),
                ('password_text', models.CharField(max_length=100)),
                ('upload_time', models.DurationField()),
                ('no_of_upload', models.IntegerField()),
                ('no_of_tamper', models.IntegerField()),
                ('client_ip', models.GenericIPAddressField(unpack_ipv4=True)),
            ],
        ),
    ]
