# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Original_DB',
        ),
        migrations.DeleteModel(
            name='User_table',
        ),
    ]
