# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170325_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hash_table',
        ),
    ]
