# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%d')),
                ('hashval', models.CharField(db_index=True, editable=False, max_length=128, null=True, unique=True)),
                ('imgsize', models.IntegerField(editable=False)),
                ('studentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.StudentInfo')),
            ],
        ),
    ]
