# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20170325_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%d')),
                ('hashval', models.CharField(db_index=True, editable=False, max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
