# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20170328_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannedimage',
            name='hashval',
        ),
    ]
