# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_remove_scannedimage_hashval'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedimage',
            name='hashval',
            field=models.CharField(db_index=True, editable=False, max_length=128, null=True),
        ),
    ]
