# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheetMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sect_no', models.IntegerField()),
                ('ques_no', models.IntegerField()),
                ('mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswersheetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.FileField(upload_to='', verbose_name=models.Model)),
                ('centrecode', models.FileField(upload_to='', verbose_name=models.Model)),
                ('answercolumn', models.FileField(upload_to='', verbose_name=models.Model)),
                ('completetemplate', models.FileField(upload_to='', verbose_name=models.Model)),
            ],
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examcode', models.CharField(max_length=100, unique=True)),
                ('exam_name', models.CharField(max_length=100, unique=True)),
                ('modelanstemplate', models.FileField(null=True, upload_to='')),
                ('exam_date', models.DateField(null=True)),
                ('templateinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.AnswersheetTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.CharField(max_length=10, null=True, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('examid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamInfo')),
            ],
        ),
        migrations.AddField(
            model_name='answersheetmarks',
            name='examid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.ExamInfo'),
        ),
        migrations.AddField(
            model_name='answersheetmarks',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.StudentInfo'),
        ),
    ]
