# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Final_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sect_no', models.IntegerField()),
                ('ques_no', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('examid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam_table')),
            ],
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('centre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='final_marks',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Student_info'),
        ),
    ]
