# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20170329_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinfo',
            name='template',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
